### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by zopyx** [collective/plone.jsonapi.core#16]
There is an example unter "Permissions" using 'object' instead of 'context'

if not getSecurityManager().checkPermission("ViewHelloAPI", object):

**Comment by zopyx** [comment]
https://github.com/collective/plone.jsonapi.core/commit/eb2fc3ca2396b3bcbe23e2a05c4c31567aa52012

**Comment by ramonski** [comment]
Thanks!
