### ISSUE TITLE
Error handling inside API method

### ISSUE THREAD

**Issue by zopyx** [collective/plone.jsonapi.core#17]
Errors that occur within an API method implementation are transported back to the client including traceback. I am not sure if this makes sense from the security point of view. More important: errors do not show up on the service side - neither inside the error_log nor within the instance log. This is bad...how should we detect broken API method implementations?

**Comment by ramonski** [comment]
Definitely, this is something which needs to be fixed. I really don't like it either!

It would be nice to send a more "friendly" error message back to the client and print the whole traceback in the server log.

Anyhow, the JSON view should never break with a traceback. So catching the error and not re-raising it makes sense.

https://github.com/collective/plone.jsonapi.core/blob/master/src/plone/jsonapi/core/browser/decorators.py#L21

The easiest way would be a simple print of the traceback, but maybe there is a better solution;)

**Comment by zopyx** [comment]
In particular: a 200 response is returned in case of an error...this is completely odd.

**Comment by ramonski** [comment]
Yes, I have to admit that I didn't changed it in the core. For the `plone.jsonapi.routes` package, I do this:

https://github.com/collective/plone.jsonapi.routes/blob/master/src/plone/jsonapi/routes/exceptions.py#L9

https://github.com/collective/plone.jsonapi.routes/blob/master/src/plone/jsonapi/routes/api.py#L55

This code should be ported into the core to return a proper status code.

**Comment by ramonski** [comment]
The `plone.jsonapi.core` package needs definitely some love:(

**Comment by ramonski** [comment]
Tracebacks are now printed on the server console and are not returned back to the client
