### ISSUE TITLE
No check for 'None' 

### ISSUE THREAD

**Issue by zopyx** [collective/plone.jsonapi.core#18]
This is the common traceback when you don't return a dict from an API call.
The decorator should check for None and provide a more helpful error message like "API methods must return a dict".

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.jsonapi.core.browser.api, line 64, in **call**
  Module plone.jsonapi.core.browser.decorators, line 47, in decorator
  Module plone.jsonapi.core.browser.decorators, line 33, in decorator
AttributeError: 'NoneType' object has no attribute 'update'

**Comment by ramonski** [comment]
Yes, the `@runtime` decorator assumes to always get a dictionary (or at least an instance, which has an `update` method:p) – not too nice, I agree. This should be handled better.
