### ISSUE TITLE
'endpoint' spec within add_route decorator

### ISSUE THREAD

**Issue by zopyx** [collective/plone.jsonapi.core#19]
As far as I understand the 'hello' endpoint with the add_route() call refers to a method hello().
But do I have to specify the name of the endpoint while using the add_route decorator? Isn't the API method obvious due to the decorator usage?

```
@router.add_route("/hello/<string:name>", "hello", methods=["GET"])
def hello(context, request, name="world"):
```

**Comment by zopyx** [comment]
Nonsense :-)

**Comment by ramonski** [comment]
Yes, the endpoint is the name of the function mapping and is used for the lookup.
Best way is actually to use a namespace for the endpoint, to avoid collision with other registered routes (e.g. zopyx.hello).
Btw.: See `plone.jsonapi.routes` this code in action.
