### ISSUE TITLE
Purpose of "endpoints"

### ISSUE THREAD

**Issue by zopyx** [collective/plone.jsonapi.core#20]
What is the exact purpose of the "endpoint" in add_route()?

Example

```
@router.add_route("/hello/<string:name>", "hello", methods=["GET"])
def hello(context, request, name="world"):
    return {
        "url": router.url_for("hello", values={"name": name}, force_external=True),
        "hello": name,
    }
```

I need to have several routes like

@@API/xmldirector/create
@@API/xmldirector/delete

So the endpoint would be 'xmldirector'? Right? But having multiple  routes like this

```
@router.add_route('/xmldirector/convert', 'xmldirector', methods=['POST'])
@router.add_route('/xmldirector/search', 'xmldirector', methods=['GET'])
@router.add_route('/xmldirector/export-zip', 'xmldirector', methods=['GET'])
@router.add_route('/xmldirector/delete', 'xmldirector', methods=['GET'])
@router.add_route('/xmldirector/get_metadata', 'xmldirector', methods=['GET'])
@router.add_route('/xmldirector/create', 'xmldirector', methods=['POST'])
@router.add_route('/xmldirector/set_metadata', 'xmldirector', methods=['POST'])
```

gives an error

```
AssertionError: View function mapping is overwriting an existing endpoint function: xmldirector
```

So what is the purpose of this endpoint parameter? Why do I need it and where do I need it?
The first parameter is obvious and sufficient to describe and configure the route.

**Comment by ramonski** [comment]
You can think of it more like a dictionary of function mappings, e.g.:

``` python
mappings = {
  "xmldirector.convert": <function convert>,
  "xmldirector.search": <function search>,
  ...
}
```
The endpoint allows other API packages to live side by side with yours, e.g. `plone.jsonapi.routes`

**Comment by ramonski** [comment]
see also: http://werkzeug.pocoo.org/docs/0.11/routing/
