### ISSUE TITLE
(large) binary data as parameter (in and out)

### ISSUE THREAD

**Issue by zopyx** [collective/plone.jsonapi.core#21]
It is possible to pass binary data as base64-encoded string or as HTTP body as part of a post request.
Both is fine especially with respect to large files and related memory problems when you need to base-64 encode a large file in memory. However it does not seem to be possible to return binary data as binary stream instead of a base64 encoded string.

Returning a large binary file should be possible doing something like this:

```
   from ZPublisher.Iterators import filestream_iterator
   request.response.setHeader('content-type', 'application/zip')
   request.response.setHeader('content-length', str(os.path.getsize(zip_out)))
   return filestream_iterator(zip_out)
```

**Comment by ramonski** [comment]
Currently the core api only supports JSON. So everything in the response must be JSON serializable.

Suggestion/Workaround:

Generate an URL which returns the binary stream and add it to your JSON response. The client has to do then another request to get it, but it should be fast anyhow.
